# Generated by Django 5.2.3 on 2025-06-18 03:57

from django.db import migrations


def clear_all_reviews(apps, schema_editor):
    """Clear all existing reviews from the database"""
    Review = apps.get_model('quotes', 'Review')
    Review.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_all_reviews),
    ]
