# Generated by Django 5.2.3 on 2026-04-03 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_review_approval_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
